src/app/components/organisms/FileUploader/types.ts
src/app/components/organisms/FileUploader/utils/defineFileFormats.ts
src/app/components/organisms/Tabs/Tabs.sc.ts
src/app/components/organisms/Tabs/Tabs.stories.tsx
src/app/components/organisms/Tabs/Tabs.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1052*
*The PR description goes here*
<br />
<br />

CW-1052 tabs headers

---

src/app/components/molecules/FormElementLabel/FormElementLabel.sc.ts
src/app/components/molecules/Input/Input.sc.ts
src/app/components/molecules/Input/Input.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1047*
*The PR description goes here*
<br />
<br />

CW-1047 add email and telephone prevalidation

---

src/app/components/organisms/Tabs/Tabs.sc.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1055*
*The PR description goes here*
<br />
<br />

CW-1055 fix text overflow in tabs

---

src/app/components/organisms/DatePicker/SingleDatePicker/SingleDatePicker.stories.tsx
src/app/components/organisms/DatePicker/SingleDatePicker/SingleDatePicker.tsx
src/app/components/organisms/EditableInformation/editableData/editableData.tsx
src/app/components/organisms/EditableInformation/types.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1074
- calculate if there is not enough available space to the right of the parentContainer
- if so, set the props for vertical anchored to the right, default is left. 
<br />
<br />

date picker align left/right

---

src/app/__tests__/utils/functions/objectFunctions.test.ts
src/app/utils/functions/objectFunctions.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1097
- make all 3 functions in objectFunctions generic, accepting unknown objects
- don't need to convert objects in CW to Record<string, unkwonn>
- added check that the parameters are indeed objects
- added unit test: npm run test objectFunctions
<br />
<br />

CW-1097 make object functions generic, accepting unknown types

---

src/app/components/molecules/Input/Input.tsx
src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/components/organisms/EditableInformation/mockup/editableInformationCurrency.tsx
src/app/components/organisms/EditableInformation/utils/generateValuesArray.ts
src/app/components/organisms/EditableInformation/utils/informationDataFunctions.tsx
src/app/utils/functions/financialFunctions.ts
src/app/utils/functions/validateFunctions.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1102*
*- added isDataChanged prop to the output of onSave*
*- fixed convert errors for currency*
<br />
<br />

Return isDataChanged prop and use cents to convert money objects

---

src/app/__tests__/utils/functions/dateFunctions.test.ts
src/app/components/organisms/Table/ContentCell/ContentCell.tsx
src/app/components/organisms/Table/mockup/tableColumns.tsx

**Jira link**:
https://jira.sportlink.nl/browse/CW-1007
- commissie name is converted to date because the string contains a number
- added isDate, to behave like isCurrency and isImage and only check validation if it is a date
<br />
<br />

add props isDate

---

package-lock.json
src/app/components/molecules/Input/Input.tsx
src/app/components/molecules/ScorePicker/ScorePicker.tsx
src/app/components/molecules/TimePicker/TimePicker.tsx
src/app/components/organisms/DropdownSelect/DropdownSelect.tsx
src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/components/organisms/EditableInformation/editableData/editableData.tsx
src/app/components/organisms/InputCurrency/InputCurrency.tsx

**Jira link**:
https://jira.sportlink.nl/browse/CW-1113
https://jira.sportlink.nl/browse/CW-1111
- make sure the component input re-renders when props changes. because we give the component the local state instead of the props we need to make sure it changes. so instead of setting the prop to be a default value to the state that stays the same the whole life of the component we use useEffect to make sure the state updates. 
- add autoFocus to the first editable input in de editableData
- added autoFocus to some input component that were missing it.
- 
<br />
<br />

component need to rerender on props change

---

src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/components/organisms/InformationTable/InformationTable.stories.tsx
src/app/components/organisms/InformationTable/InformationTable.tsx
src/app/components/organisms/InformationTable/components/Information.sc.ts
src/app/components/organisms/InformationTable/components/InformationErrors.sc.ts
src/app/components/organisms/InformationTable/components/InformationWarnings.sc.ts
src/app/components/organisms/InformationTable/components/InformationWarnings.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1116*
*- added support for warnings next to errors*
<br />
<br />

Added support for warning messages

---

src/app/components/organisms/FileUploadDialog/FileUploadDialog.stories.tsx
src/app/components/organisms/FileUploader/types.ts
src/app/components/organisms/FileUploader/utils/defineFileFormats.ts
src/app/utils/functions/fileFunctions.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1115*
*- better support for various file types*
<br />
<br />

Fb cw 1115 filetype

---

src/app/components/atoms/SelectOption/SelectOption.sc.ts
src/app/components/atoms/SelectOption/SelectOption.stories.tsx
src/app/components/atoms/SelectOption/SelectOption.tsx
src/app/components/molecules/Dropdown/Dropdown.stories.tsx
src/app/components/molecules/Dropdown/Dropdown.tsx
src/app/components/molecules/TimePicker/TimePicker.tsx
src/app/components/organisms/DatePicker/Navigation/Navigation.tsx
src/app/components/organisms/Table/Paginator/Paginator.tsx

Note: this should be handled natively somehow, but searching the internet only resulted in confirmation of this problem
**Jira link**:
*https://jira.sportlink.nl/browse/CW-1144*
*- implemented a styled version of HTML option *
<br />
<br />

Created a styled option instead of the native version

---

src/app/__tests__/utils/functions/arrayObjectFunctions.test.ts
src/app/components/molecules/Dropdown/Dropdown.stories.tsx
src/app/components/molecules/Dropdown/mockup/data.ts
src/app/components/organisms/DropdownSelect/DropdownSelect.stories.tsx
src/app/components/organisms/DropdownSelect/mockup/data.tsx
src/app/utils/functions/arrayObjectFunctions.ts
src/lib/index.ts

**Jira link**:
*-*
*- in order to have an easy way of getting an option from the option ist, created a function for it*
<br />
<br />

Added some tests and a function getDropdownSelectOption

---

src/app/components/organisms/EditableInformation/mockup/editableInformationData.tsx
src/app/components/organisms/EditableInformation/utils/generateValuesArray.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1164
add textValue to generated values array also for regular dropdown
<br />
<br />

CW-1164  textValue in generated values array also for regular dropdown

---

.eslintrc.js
src/app/components/molecules/Input/Input.tsx
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.sc.ts
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.stories.tsx
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.tsx
src/app/types.ts

*Made some changes to the control group component*
**Jira link**:
*https://jira.sportlink.nl/browse/CW-1165*
*- replaced hasBorder with a variant type*
*- added Alignment option*
*- some styling issues fixed*
<br />
<br />

Selection control group changes

---

.eslintrc.js
src/app/components/molecules/Input/Input.tsx
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.sc.ts
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.stories.tsx
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.tsx
src/app/components/organisms/Table/ContentCell/ContentCell.sc.ts
src/app/components/organisms/Table/ContentCell/ContentCell.tsx
src/app/components/organisms/Table/mockup/tableColumns.tsx
src/app/types.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1167*
*- handle negative amounts*
<br />
<br />

Fb contentcell

---

src/@types/react-table.d.ts
src/app/components/organisms/Table/ContentCell/ContentCell.tsx
src/app/components/organisms/Table/Table.sc.ts
src/app/components/organisms/Table/Table.tsx
src/app/components/organisms/Table/mockup/tableColumns.tsx
src/app/components/organisms/Table/mockup/tableData.ts

**Jira link**:
*No issue*
*- applied logic to have currency styling in footer*
*- in order ot do that, added props to TableInstance and ColumnInstance*
<br />
<br />

Added aggregate styling for currency

---

src/@types/react-table.d.ts
src/app/components/organisms/Table/Table.stories.tsx
src/app/components/organisms/Table/Table.tsx
src/app/components/organisms/Table/mockup/tableColumns.tsx
src/app/components/organisms/Table/mockup/tableData.ts
src/app/utils/functions/createTable.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1201*
*Some locale issues with table*
<br />
<br />

Fixed locale issues with table

---

package-lock.json
src/app/components/molecules/Dropdown/Dropdown.sc.ts
src/app/components/molecules/Input/Input.sc.ts
src/app/components/organisms/DatePicker/DateRangePicker/DateRangePicker.stories.tsx
src/app/components/organisms/DatePicker/DateRangePicker/DateRangePicker.tsx
src/app/components/organisms/DatePicker/SingleDatePicker/SingleDatePicker.sc.ts
src/app/components/organisms/DatePicker/SingleDatePicker/SingleDatePicker.tsx
src/app/components/organisms/DatePicker/Wrapper/Wrapper.sc.ts
src/app/components/organisms/DatePicker/Wrapper/Wrapper.tsx
src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/styles/mixins/getBorderColor.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1211*
*- fixed border thickness when not focused for Input, Dropdown and DatePicker*
<br />
<br />

CW-1211: fixed some borders

---

src/@types/react-table.d.ts
src/app/__tests__/utils/functions/tableFunctions.test.ts
src/app/components/molecules/SelectionControl/SelectionControl.sc.ts
src/app/components/molecules/SelectionControl/SelectionControl.stories.tsx
src/app/components/molecules/SelectionControl/SelectionControl.tsx
src/app/components/organisms/Table/Paginator/Paginator.stories.tsx
src/app/components/organisms/Table/RowSelectionCheckbox/RowSelectionCheckbox.sc.ts
src/app/components/organisms/Table/RowSelectionCheckbox/RowSelectionCheckbox.tsx
src/app/components/organisms/Table/StatusCell/StatusCell.tsx
src/app/components/organisms/Table/Table.stories.tsx
src/app/components/organisms/Table/Table.tsx
src/app/components/organisms/Table/mockup/tableColumns.tsx
src/app/components/organisms/Table/mockup/tableData.ts
src/app/components/organisms/Table/utils/tableFunctions.tsx
src/app/styles/mixins/getStatusIndicator.ts
src/app/styles/theming/themes/basic.ts
src/app/styles/theming/themes/cyrillic.ts
src/app/styles/theming/themes/dark.ts
src/app/types.ts
src/app/utils/functions/createTable.tsx
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1142*
*- added multiselect option to Table component*
*- added functions for convenience usage: getSelectedRows and getSelectedRowIds*
*- adjusted StatusCell component so it has an optional status indicator*
<br />
<br />

Fb cw 1142 multiselect table

---

src/app/__tests__/utils/functions/validateFunctions.test.ts
src/app/utils/functions/validateFunctions.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1234*
*- added isValidIBAN function*
*- implemented tests for several validation functions*
<br />
<br />

CW-1234: Added IBAN validator

---

package-lock.json
package.json
src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/components/organisms/EditableInformation/editableData/editableData.tsx
src/app/components/organisms/EditableInformation/utils/informationDataFunctions.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1217*
*- added localeCurrency so we can set this seperately (defaults to locale)*
<br />
<br />

CW-1217: Introduced a specific currency locale for editable information

---

src/app/components/molecules/SelectionControl/SelectionControl.sc.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1141*
*- resizing option SMALL has changed*
<br />
<br />

Checkbox SMALL a little smaller

---

src/app/components/molecules/DialogFooter/DialogFooter.sc.ts
src/app/components/organisms/Dialog/Dialog.sc.ts
src/app/components/organisms/Dialog/Dialog.tsx
src/app/components/organisms/EditableInformation/mockup/editableInformationCurrency.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1207*
*- positioning the icon and text according to designer specs*
<br />
<br />

Fb cw 1207 dialog icon positioning

---

src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.stories.tsx
src/app/components/molecules/SelectionControlGroup/SelectionControlGroup.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/types.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1238*
*- added isDisabled to the OptionObject interface*
<br />
<br />

CW-1238: added isDisabled prop to the OptionObject

---

src/app/components/organisms/DatePicker/Wrapper/Wrapper.sc.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1263*
*- fixed text color for date input*
<br />
<br />

Fb cw 1263 input color dates

---

src/app/__tests__/utils/functions/validateFunctions.test.ts
src/app/components/molecules/Input/Input.tsx
src/app/components/organisms/EditableInformation/utils/informationDataFunctions.tsx
src/app/utils/functions/validateFunctions.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1262
check the unit test for what is valid telefphone number now and what is not. 
<br />
<br />

CW-1262 change validation telephone number

---

src/app/components/organisms/Table/Table.stories.tsx
src/app/utils/functions/createTable.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1285*
*- Added functionality for optional minimum and maximum select counters*
<br />
<br />

CW-1285: Added functionality to have a minimum and maximum selected check

---

src/app/components/molecules/DialogFooter/DialogFooter.sc.ts
src/app/components/molecules/DialogFooter/DialogFooter.tsx
src/app/components/organisms/Dialog/Dialog.sc.ts
src/app/components/organisms/Dialog/Dialog.stories.tsx
src/app/components/organisms/Dialog/Dialog.tsx
src/app/types.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1296*
*- isScrollable should adjust some other parts, so implemented it*
<br />
<br />

Scrollable in dialog a bit better

---

src/app/components/molecules/DialogFooter/DialogFooter.sc.ts
src/app/components/molecules/DialogFooter/DialogFooter.tsx

**Jira link**:
https://jira.sportlink.nl/browse/CW-1322
add check if text is empty to the styled component
<br />
<br />

CW-1322 align buttons also when there is no text

---

src/app/components/organisms/InformationTable/InformationTable.stories.tsx
src/app/components/organisms/InformationTable/InformationTable.tsx

**Jira link**:
needed for https://jira.sportlink.nl/browse/CW-1130
for showing skeletons in 2 columns in InformationTable
- property isLoadig, optional
- if the data is empty or isLoading generate skeleton array
- add isLoading to the story
<br />
<br />

Fb information table prop is loading

---

src/app/components/organisms/Dialog/Dialog.tsx
src/app/components/organisms/FileUploadDialog/FileUploadDialog.sc.ts
src/app/components/organisms/FileUploadDialog/FileUploadDialog.stories.tsx
src/app/components/organisms/FileUploadDialog/FileUploadDialog.tsx
src/app/components/organisms/FileUploader/FileUploader.sc.ts
src/app/components/organisms/FileUploader/FileUploader.stories.tsx
src/app/components/organisms/FileUploader/FileUploader.tsx
src/app/components/organisms/FileUploader/types.ts
src/app/components/organisms/FileUploader/utils/getTranslations.ts
src/app/utils/functions/fileFunctions.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1324
- fix bug in the ticket
- refactor: remove all useRef to DOM element, it wasn't needed. can just use element onDrag, onDrop instead of addEventListener on a ref.
- refactor styling
- add hasThumbnail
<br />
<br />

CW-1324 refactor file upload dialog no use ref

---

src/app/components/molecules/Input/Input.tsx
src/app/styles/fonts/iconfont/iconfont.css

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1338*
*Set the local state value on loading and when it changes.*
*This prevents having no value in onBlur when not changing anything.*
<br />
<br />

Fb cw 1338 fix currency issue

---

package-lock.json
package.json
src/app/components/molecules/DialogFooter/DialogFooter.sc.ts
src/app/components/organisms/PicklistMultiSelect/PicklistMultiSelect.stories.tsx
src/app/components/organisms/PicklistMultiSelect/PicklistMultiSelect.tsx

Already published so I can use it, but if changes required, just republish
**Jira link**:
*https://jira.sportlink.nl/browse/CW-1345*
*- new design required footer text per panel*
<br />
<br />

Fb cw 1345 picklist footer

---

src/app/components/organisms/Table/mockup/tableData.ts
src/app/utils/functions/createTable.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1355*
*- the header checkbox in multi select table shouldn't be checked when no available rows left*
<br />
<br />

Fb cw 1355 rowselection

---

src/app/__tests__/utils/functions/validateFunctions.test.ts
src/app/components/molecules/Input/Input.tsx
src/app/components/organisms/EditableInformation/utils/informationDataFunctions.tsx
src/app/types.ts
src/app/utils/functions/validateFunctions.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1356*
*- added regex for uri*
<br />
<br />

Added URI validating

---

src/app/components/molecules/Input/Input.stories.tsx
src/app/components/molecules/Input/Input.tsx
src/app/components/molecules/Input/component/TextField.sc.ts
src/app/components/organisms/FileUploadDialog/FileUploadDialog.stories.tsx
src/app/components/organisms/FileUploadDialog/FileUploadDialog.tsx
src/app/components/organisms/FileUploader/FileCard/FileCard.sc.ts
src/app/components/organisms/FileUploader/FileCard/FileCard.tsx
src/app/components/organisms/FileUploader/FileUploader.sc.ts
src/app/components/organisms/FileUploader/FileUploader.stories.tsx
src/app/components/organisms/FileUploader/FileUploader.tsx
src/app/components/organisms/FileUploader/index.ts
src/app/components/organisms/FileUploader/types.ts
src/app/components/organisms/FileUploader/utils/fileFormatsFunctions.ts
src/app/components/organisms/FileUploader/utils/getTranslations.ts
src/lib/index.ts

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1336
NOTE breaking changes to CW
- refactor component according to new design
- created component FileCard to show the icon/thumbnail (depending on type) name, size, error if exists, button to delete or upload icon.
- the error is always shown on the last uploaded file because it is always the last one that causes the error
- every time a file is deleted validation all the files again because maybe the file that was deleted wasn't the last file causing the error.
design one file upload:
https://projects.invisionapp.com/d/main#/console/20400204/439727342/preview
design multiple file upload:
https://projects.invisionapp.com/d/main?origin=v7#/console/18016777/423772844/preview?scrollOffset=889
<br />
<br …

CW-1336 refactor file uploader new design

---

src/app/__tests__/utils/functions/linkFunctions.test.ts
src/app/utils/functions/linkFunctions.ts

**Jira link**:
https://jira.sportlink.nl/browse/CW-1369
instead of checking if the uri doesn't start with 'https://' check if the url starts witl www and if it does add https:// to it.
otherwise just leave it as it is. so if it starts with https:// or http:// the prefix won't be added
<br />
<br />

CW-1369 changed condition to include http

---

src/app/components/molecules/CloseablePanel/CloseablePanel.stories.tsx
src/app/components/molecules/CloseablePanel/CloseablePanel.tsx
src/app/components/molecules/Header/Header.stories.tsx
src/app/components/molecules/PanelHeader/PanelHeader.sc.ts
src/app/components/molecules/PanelHeader/PanelHeader.stories.tsx
src/app/components/molecules/PanelHeader/PanelHeader.tsx
src/app/components/molecules/PanelStatus/PanelStatus.stories.tsx
src/app/components/molecules/PanelStatus/PanelStatus.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/components/organisms/EditablePanel/EditablePanel.stories.tsx
src/app/components/organisms/EditablePanel/EditablePanel.tsx

Design: https://projects.invisionapp.com/d/main?origin=v7#/console/18016777/387368832/preview?scrollOffset=600
**Jira link**:
*https://jira.sportlink.nl/browse/CW-1366*
*- make header loading state*
<br />
<br />

Fb cw 1366 loading state headers

---

src/app/__tests__/utils/functions/validateFunctions.test.ts
src/app/styles/fonts/iconfont/iconfont.css
src/app/utils/functions/validateFunctions.ts

**Jira link**:
*No issue*
*- fixed uri validating with regex*
<br />
<br />

Fixed uri regex

---

src/app/components/molecules/Input/Input.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1344*
*- handle number validation completely in component*
<br />
<br />

CW-1344: workaround for input type number bug

---

src/app/components/organisms/DropdownMultiSelect/DropdownMultiSelect.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-218*
*- made a complete row clickable*
<br />
<br />

CW-218: added onClick for complete row

---

src/app/components/organisms/EditableInformation/EditableInformation.stories.tsx
src/app/components/organisms/EditableInformation/EditableInformation.tsx
src/app/components/organisms/EditablePanel/EditablePanel.sc.ts
src/app/components/organisms/EditablePanel/EditablePanel.tsx

**Jira link**:
*https://jira.sportlink.nl/browse/CW-1471*
*- support for additional buttons through the options property*
<br />
<br />

CW-1471: added options support and return edit mode value
